from django.db import models
from django.utils import timezone

class Movie(models.Model):
    Title = models.CharField(max_length=200, null=True)
    Year = models.CharField(max_length=6, null=True)
    Runtime = models.CharField(max_length=20, null=True)
    Genre = models.CharField(max_length=100, null=True)
    Director = models.CharField(max_length=100, null=True)
    Actors = models.TextField(null=True)
    imdbRating = models.CharField(max_length=10, null=True)
    Type = models.CharField(max_length=10, null=True)
    Poster = models.TextField(null=True)
    tomatoConsensus = models.TextField(null=True)
    tomatoMeter = models.CharField(max_length=10, null=True)
    Metascore = models.CharField(max_length=10, null=True)
    Website = models.TextField(null=True)
    Plot = models.TextField(null=True)
    Error = models.TextField(null=True)
    Response = models.TextField(null=True)    
    Language = models.TextField(null=True)
    Metascore = models.TextField(null=True)
    Type = models.TextField(null=True)    
    tomatoImage = models.TextField(null=True)
    tomatoUserRating = models.TextField(null=True)
    Production = models.TextField(null=True)
    tomatoFresh = models.TextField(null=True)
    tomatoUserMeter = models.TextField(null=True)
    BoxOffice = models.TextField(null=True)
    Released = models.TextField(null=True)
    Awards = models.TextField(null=True)
    DVD = models.TextField(null=True)
    tomatoURL = models.TextField(null=True)
    totalSeasons = models.TextField(null=True)
    tomatoRating = models.TextField(null=True)
    imdbID = models.TextField(null=True)
    tomatoRotten = models.TextField(null=True)
    Country = models.TextField(null=True)
    imdbVotes = models.TextField(null=True)
    tomatoReviews = models.TextField(null=True)
    tomatoUserReviews = models.TextField(null=True)
    Writer = models.TextField(null=True)
    Rated = models.TextField(null=True)

    def __str__(self):
        return self.Title                     
