# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-03 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=6)),
                ('runtime', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('imdbRating', models.CharField(max_length=10)),
                ('rated', models.CharField(max_length=10)),
                ('poster', models.TextField()),
                ('movType', models.CharField(max_length=30)),
                ('tomatoConsensus', models.TextField()),
                ('tomatoMeter', models.CharField(max_length=10)),
                ('avg', models.CharField(max_length=10)),
                ('website', models.TextField()),
                ('plot', models.TextField()),
            ],
        ),
    ]
